// TAB-1 — Apprendre Excel pas à pas : les 13 étapes et leurs corrigés.
//
// ⚠️ FICHIER GÉNÉRÉ — ne pas modifier à la main.
// Source : outils/tab1-exercices.mjs, à relancer après toute modification :
//     node outils/tab1-exercices.mjs
//
// Repris de la Suite Logistique (module C-1). 137 contrôles répartis sur
// 11 étapes corrigées automatiquement ; 2 étapes
// (mise en forme conditionnelle, graphique) se vérifient en classe et ne comptent pas
// dans le score. Les classeurs modèles sont dans contenus/tab1/, l'onglet « Correction »
// de la Suite leur ayant été retiré (voir outils/tab1-modeles.py).
//
// Le champ `niveaux` est propre à chaque étape : un élève ne voit que celles de son
// niveau de classe. Modifier une ligne du générateur suffit à en déplacer une.

export const EXERCICES = [
  {
    id: "et01",
    titre: "1 — Découvrir Excel et saisir des données",
    groupe: "PREMIERS PAS",
    objectif: "Se repérer dans une feuille et saisir des informations sans erreur.",
    niveaux: ["2de","1re","tle","cap"],
    fichier: "et01-decouvrir-excel.xlsx",
    controles: [
    { cellule: "B2", libelle: "Désignation ligne 2", attendu: "Carton de conserves" },
    { cellule: "B3", libelle: "Désignation ligne 3", attendu: "Lot de T-shirts" },
    { cellule: "B4", libelle: "Désignation ligne 4", attendu: "Carton d'ampoules LED" },
    { cellule: "B5", libelle: "Désignation ligne 5", attendu: "Caisse à outils" },
    { cellule: "B6", libelle: "Désignation ligne 6", attendu: "Ramettes de papier A4" },
    { cellule: "B7", libelle: "Désignation ligne 7", attendu: "Pack de bouteilles d'eau" },
    { cellule: "B8", libelle: "Désignation ligne 8", attendu: "Casque de chantier" },
    { cellule: "B9", libelle: "Désignation ligne 9", attendu: "Rouleau de film étirable" },
    { cellule: "B10", libelle: "Désignation ligne 10", attendu: "Gants de manutention" },
    { cellule: "B11", libelle: "Désignation ligne 11", attendu: "Palette bois" },
    { cellule: "B12", libelle: "Désignation ligne 12", attendu: "Carton d'emballage" },
    { cellule: "B13", libelle: "Désignation ligne 13", attendu: "Étiquettes code-barres" },
    ],
  },
  {
    id: "et02",
    titre: "2 — Écrire sa première formule",
    groupe: "FORMULES",
    objectif: "Comprendre ce qu'est une formule et utiliser une référence de cellule.",
    niveaux: ["2de","1re","tle","cap"],
    fichier: "et02-premiere-formule.xlsx",
    controles: [
    { cellule: "E2", libelle: "Montant ligne 2", attendu: 28, tolerance: 0.02, formuleAttendue: true },
    { cellule: "E3", libelle: "Montant ligne 3", attendu: 50.4, tolerance: 0.02, formuleAttendue: true },
    { cellule: "E4", libelle: "Montant ligne 4", attendu: 42, tolerance: 0.02, formuleAttendue: true },
    { cellule: "E5", libelle: "Montant ligne 5", attendu: 32, tolerance: 0.02, formuleAttendue: true },
    { cellule: "E6", libelle: "Montant ligne 6", attendu: 27, tolerance: 0.02, formuleAttendue: true },
    { cellule: "E7", libelle: "Montant ligne 7", attendu: 32.5, tolerance: 0.02, formuleAttendue: true },
    ],
  },
  {
    id: "et03",
    titre: "3 — Tirer une formule (la recopier)",
    groupe: "FORMULES",
    objectif: "Recopier une formule vers le bas et vers la droite sans la retaper.",
    niveaux: ["2de","1re","tle","cap"],
    fichier: "et03-tirer-formule.xlsx",
    controles: [
    { cellule: "D3", libelle: "Montant ligne 3", attendu: 35, tolerance: 0.02, formuleAttendue: true },
    { cellule: "D4", libelle: "Montant ligne 4", attendu: 60, tolerance: 0.02, formuleAttendue: true },
    { cellule: "D5", libelle: "Montant ligne 5", attendu: 36, tolerance: 0.02, formuleAttendue: true },
    { cellule: "D6", libelle: "Montant ligne 6", attendu: 50, tolerance: 0.02, formuleAttendue: true },
    { cellule: "D7", libelle: "Montant ligne 7", attendu: 66, tolerance: 0.02, formuleAttendue: true },
    { cellule: "D8", libelle: "Montant ligne 8", attendu: 75, tolerance: 0.02, formuleAttendue: true },
    { cellule: "B13", libelle: "Prix TTC produit 1", attendu: 60, tolerance: 0.02, formuleAttendue: true },
    { cellule: "C13", libelle: "Prix TTC produit 2", attendu: 96, tolerance: 0.02, formuleAttendue: true },
    { cellule: "D13", libelle: "Prix TTC produit 3", attendu: 144, tolerance: 0.02, formuleAttendue: true },
    { cellule: "E13", libelle: "Prix TTC produit 4", attendu: 240, tolerance: 0.02, formuleAttendue: true },
    ],
  },
  {
    id: "et04",
    titre: "4 — Figer une cellule avec F4",
    groupe: "FORMULES",
    objectif: "Empêcher une référence de bouger quand on recopie une formule.",
    niveaux: ["2de","1re","tle","cap"],
    fichier: "et04-figer-cellule.xlsx",
    controles: [
    { cellule: "C7", libelle: "Coût du trajet ligne 7", attendu: 96, tolerance: 0.02, formuleAttendue: true },
    { cellule: "C8", libelle: "Coût du trajet ligne 8", attendu: 44, tolerance: 0.02, formuleAttendue: true },
    { cellule: "C9", libelle: "Coût du trajet ligne 9", attendu: 36, tolerance: 0.02, formuleAttendue: true },
    { cellule: "C10", libelle: "Coût du trajet ligne 10", attendu: 200, tolerance: 0.02, formuleAttendue: true },
    { cellule: "C11", libelle: "Coût du trajet ligne 11", attendu: 192, tolerance: 0.02, formuleAttendue: true },
    { cellule: "C12", libelle: "Coût du trajet ligne 12", attendu: 128, tolerance: 0.02, formuleAttendue: true },
    ],
  },
  {
    id: "et05",
    titre: "5 — Comprendre et utiliser une plage",
    groupe: "FORMULES",
    objectif: "Découvrir la notion de plage (C2:C7) à travers SOMME, MIN et MAX.",
    niveaux: ["2de","1re","tle","cap"],
    fichier: "et05-comprendre-plage.xlsx",
    controles: [
    { cellule: "C9", libelle: "Total des quantités", attendu: 180, formuleAttendue: true },
    { cellule: "C10", libelle: "Quantité minimale", attendu: 8, formuleAttendue: true },
    { cellule: "C11", libelle: "Quantité maximale", attendu: 60, formuleAttendue: true },
    ],
  },
  {
    id: "et06",
    titre: "6 — Additionner et calculer une moyenne",
    groupe: "FONCTIONS",
    objectif: "Utiliser SOMME et MOYENNE sur des quantités en stock.",
    niveaux: ["2de","1re","tle","cap"],
    fichier: "et06-somme-moyenne.xlsx",
    controles: [
    { cellule: "C18", libelle: "Total des quantités", attendu: 273, formuleAttendue: true },
    { cellule: "C19", libelle: "Moyenne des quantités", attendu: 18.2, tolerance: 0.02, formuleAttendue: true },
    ],
  },
  {
    id: "et07",
    titre: "7 — La fonction SI, premiers pas",
    groupe: "FONCTIONS",
    objectif: "Découvrir SI sur un cas simple à 5 lignes, une seule condition.",
    niveaux: ["2de","1re","tle","cap"],
    fichier: "et07-si-premiers-pas.xlsx",
    controles: [
    { cellule: "E7", libelle: "Faut-il commander ? ligne 7", attendu: false, formuleAttendue: true },
    { cellule: "E8", libelle: "Faut-il commander ? ligne 8", attendu: true, formuleAttendue: true },
    { cellule: "E9", libelle: "Faut-il commander ? ligne 9", attendu: false, formuleAttendue: true },
    { cellule: "E10", libelle: "Faut-il commander ? ligne 10", attendu: true, formuleAttendue: true },
    { cellule: "E11", libelle: "Faut-il commander ? ligne 11", attendu: false, formuleAttendue: true },
    ],
  },
  {
    id: "et08",
    titre: "8 — La fonction SI",
    groupe: "FONCTIONS",
    objectif: "Faire prendre une décision automatique à Excel selon une condition.",
    niveaux: ["2de","1re","tle","cap"],
    fichier: "et08-fonction-si.xlsx",
    controles: [
    { cellule: "E2", libelle: "Statut ligne 2", attendu: "OK" },
    { cellule: "E3", libelle: "Statut ligne 3", attendu: "À commander" },
    { cellule: "E4", libelle: "Statut ligne 4", attendu: "À commander" },
    { cellule: "E5", libelle: "Statut ligne 5", attendu: "OK" },
    { cellule: "E6", libelle: "Statut ligne 6", attendu: "OK" },
    { cellule: "E7", libelle: "Statut ligne 7", attendu: "À commander" },
    { cellule: "E8", libelle: "Statut ligne 8", attendu: "OK" },
    { cellule: "E9", libelle: "Statut ligne 9", attendu: "À commander" },
    { cellule: "E10", libelle: "Statut ligne 10", attendu: "OK" },
    { cellule: "E11", libelle: "Statut ligne 11", attendu: "À commander" },
    { cellule: "E12", libelle: "Statut ligne 12", attendu: "OK" },
    { cellule: "E13", libelle: "Statut ligne 13", attendu: "À commander" },
    { cellule: "E14", libelle: "Statut ligne 14", attendu: "OK" },
    { cellule: "E15", libelle: "Statut ligne 15", attendu: "OK" },
    { cellule: "E16", libelle: "Statut ligne 16", attendu: "À commander" },
    ],
  },
  {
    id: "et09",
    titre: "9 — Mise en forme conditionnelle",
    groupe: "MISE EN FORME",
    objectif: "Colorer automatiquement les lignes à recommander.",
    niveaux: ["2de","1re","tle","cap"],
    fichier: "et09-mise-en-forme-conditionnelle.xlsx",
    // Pas de contrôle : se vérifie en classe, et ne compte pas dans le score.
    controles: [],
  },
  {
    id: "et10",
    titre: "10 — Créer un graphique",
    groupe: "MISE EN FORME",
    objectif: "Représenter le stock sous forme de graphique en barres.",
    niveaux: ["2de","1re","tle","cap"],
    fichier: "et10-graphique.xlsx",
    // Pas de contrôle : se vérifie en classe, et ne compte pas dans le score.
    controles: [],
  },
  {
    id: "et11",
    titre: "11 — Cas concret : tableau de bord de stock",
    groupe: "CAS COMPLET",
    objectif: "Combiner toutes les compétences sur un cas complet de gestion de stock.",
    niveaux: ["2de","1re","tle","cap"],
    fichier: "et11-tableau-de-bord.xlsx",
    controles: [
    { cellule: "F2", libelle: "Valeur du stock ligne 2", attendu: 28.8, tolerance: 0.05, formuleAttendue: true },
    { cellule: "G2", libelle: "Statut ligne 2", attendu: "OK" },
    { cellule: "F3", libelle: "Valeur du stock ligne 3", attendu: 85, tolerance: 0.05, formuleAttendue: true },
    { cellule: "G3", libelle: "Statut ligne 3", attendu: "À commander" },
    { cellule: "F4", libelle: "Valeur du stock ligne 4", attendu: 74.5, tolerance: 0.05, formuleAttendue: true },
    { cellule: "G4", libelle: "Statut ligne 4", attendu: "À commander" },
    { cellule: "F5", libelle: "Valeur du stock ligne 5", attendu: 576, tolerance: 0.05, formuleAttendue: true },
    { cellule: "G5", libelle: "Statut ligne 5", attendu: "OK" },
    { cellule: "F6", libelle: "Valeur du stock ligne 6", attendu: 172, tolerance: 0.05, formuleAttendue: true },
    { cellule: "G6", libelle: "Statut ligne 6", attendu: "OK" },
    { cellule: "F7", libelle: "Valeur du stock ligne 7", attendu: 9.3, tolerance: 0.05, formuleAttendue: true },
    { cellule: "G7", libelle: "Statut ligne 7", attendu: "À commander" },
    { cellule: "F8", libelle: "Valeur du stock ligne 8", attendu: 77, tolerance: 0.05, formuleAttendue: true },
    { cellule: "G8", libelle: "Statut ligne 8", attendu: "OK" },
    { cellule: "F9", libelle: "Valeur du stock ligne 9", attendu: 13.5, tolerance: 0.05, formuleAttendue: true },
    { cellule: "G9", libelle: "Statut ligne 9", attendu: "À commander" },
    { cellule: "F10", libelle: "Valeur du stock ligne 10", attendu: 52.8, tolerance: 0.05, formuleAttendue: true },
    { cellule: "G10", libelle: "Statut ligne 10", attendu: "OK" },
    { cellule: "F11", libelle: "Valeur du stock ligne 11", attendu: 54, tolerance: 0.05, formuleAttendue: true },
    { cellule: "G11", libelle: "Statut ligne 11", attendu: "À commander" },
    { cellule: "F12", libelle: "Valeur du stock ligne 12", attendu: 46.75, tolerance: 0.05, formuleAttendue: true },
    { cellule: "G12", libelle: "Statut ligne 12", attendu: "OK" },
    { cellule: "F13", libelle: "Valeur du stock ligne 13", attendu: 50.4, tolerance: 0.05, formuleAttendue: true },
    { cellule: "G13", libelle: "Statut ligne 13", attendu: "À commander" },
    { cellule: "F14", libelle: "Valeur du stock ligne 14", attendu: 66, tolerance: 0.05, formuleAttendue: true },
    { cellule: "G14", libelle: "Statut ligne 14", attendu: "OK" },
    { cellule: "F15", libelle: "Valeur du stock ligne 15", attendu: 102.2, tolerance: 0.05, formuleAttendue: true },
    { cellule: "G15", libelle: "Statut ligne 15", attendu: "OK" },
    { cellule: "F16", libelle: "Valeur du stock ligne 16", attendu: 159.2, tolerance: 0.05, formuleAttendue: true },
    { cellule: "G16", libelle: "Statut ligne 16", attendu: "À commander" },
    { cellule: "F17", libelle: "Valeur du stock ligne 17", attendu: 49.5, tolerance: 0.05, formuleAttendue: true },
    { cellule: "G17", libelle: "Statut ligne 17", attendu: "OK" },
    { cellule: "F18", libelle: "Valeur du stock ligne 18", attendu: 76.8, tolerance: 0.05, formuleAttendue: true },
    { cellule: "G18", libelle: "Statut ligne 18", attendu: "OK" },
    { cellule: "F19", libelle: "Valeur du stock ligne 19", attendu: 75, tolerance: 0.05, formuleAttendue: true },
    { cellule: "G19", libelle: "Statut ligne 19", attendu: "À commander" },
    { cellule: "F20", libelle: "Valeur du stock ligne 20", attendu: 57, tolerance: 0.05, formuleAttendue: true },
    { cellule: "G20", libelle: "Statut ligne 20", attendu: "OK" },
    { cellule: "F21", libelle: "Valeur du stock ligne 21", attendu: 80.75, tolerance: 0.05, formuleAttendue: true },
    { cellule: "G21", libelle: "Statut ligne 21", attendu: "OK" },
    { cellule: "C23", libelle: "Total des quantités", attendu: 390, formuleAttendue: true },
    { cellule: "F23", libelle: "Valeur totale du stock", attendu: 1906.5, tolerance: 0.1, formuleAttendue: true },
    ],
  },
  {
    id: "et12",
    titre: "12 — Extraire une partie d'une référence",
    groupe: "TEXTE",
    objectif: "Découvrir GAUCHE et DROITE pour décoder une référence produit.",
    niveaux: ["2de","1re","tle","cap"],
    fichier: "et12-gauche-droite.xlsx",
    controles: [
    { cellule: "B2", libelle: "Code entrepôt ligne 2", attendu: "NIM" },
    { cellule: "C2", libelle: "Numéro de séquence ligne 2", attendu: "015" },
    { cellule: "B3", libelle: "Code entrepôt ligne 3", attendu: "LYO" },
    { cellule: "C3", libelle: "Numéro de séquence ligne 3", attendu: "102" },
    { cellule: "B4", libelle: "Code entrepôt ligne 4", attendu: "MAR" },
    { cellule: "C4", libelle: "Numéro de séquence ligne 4", attendu: "047" },
    { cellule: "B5", libelle: "Code entrepôt ligne 5", attendu: "PAR" },
    { cellule: "C5", libelle: "Numéro de séquence ligne 5", attendu: "089" },
    { cellule: "B6", libelle: "Code entrepôt ligne 6", attendu: "LIL" },
    { cellule: "C6", libelle: "Numéro de séquence ligne 6", attendu: "003" },
    { cellule: "B7", libelle: "Code entrepôt ligne 7", attendu: "NIM" },
    { cellule: "C7", libelle: "Numéro de séquence ligne 7", attendu: "156" },
    { cellule: "B8", libelle: "Code entrepôt ligne 8", attendu: "MAR" },
    { cellule: "C8", libelle: "Numéro de séquence ligne 8", attendu: "012" },
    { cellule: "B9", libelle: "Code entrepôt ligne 9", attendu: "PAR" },
    { cellule: "C9", libelle: "Numéro de séquence ligne 9", attendu: "198" },
    { cellule: "B10", libelle: "Code entrepôt ligne 10", attendu: "LYO" },
    { cellule: "C10", libelle: "Numéro de séquence ligne 10", attendu: "067" },
    { cellule: "B11", libelle: "Code entrepôt ligne 11", attendu: "LIL" },
    { cellule: "C11", libelle: "Numéro de séquence ligne 11", attendu: "041" },
    { cellule: "B12", libelle: "Code entrepôt ligne 12", attendu: "NIM" },
    { cellule: "C12", libelle: "Numéro de séquence ligne 12", attendu: "229" },
    { cellule: "B13", libelle: "Code entrepôt ligne 13", attendu: "PAR" },
    { cellule: "C13", libelle: "Numéro de séquence ligne 13", attendu: "075" },
    ],
  },
  {
    id: "et13",
    titre: "13 — Construire une référence avec CONCATENER",
    groupe: "TEXTE",
    objectif: "Assembler plusieurs informations séparées en une seule référence.",
    niveaux: ["2de","1re","tle","cap"],
    fichier: "et13-concatener.xlsx",
    controles: [
    { cellule: "D2", libelle: "Référence construite ligne 2", attendu: "NIM-24-015" },
    { cellule: "D3", libelle: "Référence construite ligne 3", attendu: "LYO-23-102" },
    { cellule: "D4", libelle: "Référence construite ligne 4", attendu: "MAR-24-047" },
    { cellule: "D5", libelle: "Référence construite ligne 5", attendu: "PAR-22-089" },
    { cellule: "D6", libelle: "Référence construite ligne 6", attendu: "LIL-24-003" },
    { cellule: "D7", libelle: "Référence construite ligne 7", attendu: "NIM-23-156" },
    { cellule: "D8", libelle: "Référence construite ligne 8", attendu: "MAR-24-012" },
    { cellule: "D9", libelle: "Référence construite ligne 9", attendu: "PAR-24-198" },
    { cellule: "D10", libelle: "Référence construite ligne 10", attendu: "LYO-22-067" },
    { cellule: "D11", libelle: "Référence construite ligne 11", attendu: "LIL-23-041" },
    { cellule: "D12", libelle: "Référence construite ligne 12", attendu: "NIM-24-229" },
    { cellule: "D13", libelle: "Référence construite ligne 13", attendu: "PAR-23-075" },
    ],
  },
];
