// TAB-2 — Excel, gestion des stocks : les 10 exercices et leurs corrigés.
//
// ⚠️ FICHIER GÉNÉRÉ — ne pas modifier à la main.
// Source : outils/tab2-exercices.mjs, à relancer après toute modification :
//     node outils/tab2-exercices.mjs
//
// Repris de la Suite Logistique (module C-2). 151 contrôles sur 10 exercices,
// tous corrigés automatiquement. Les classeurs modèles sont dans contenus/tab2/, l'onglet
// « Correction » de la Suite leur ayant été retiré (voir outils/modeles-sans-corrige.py).
//
// Les valeurs attendues portent toutes leurs décimales : la Suite comparait au produit
// brut, sans arrondi intermédiaire, et les tolérances (0,02 sur un prix, 0,05 sur une valeur,
// 0,1 sur un total, 0,5 sur un total de TCD) sont les siennes.
//
// Le champ `niveaux` est propre à chaque exercice : absent, l'exercice est ouvert à tous les
// niveaux (c'est le cas des dix). Ajouter `niveaux` à l'exercice dans le générateur suffit à
// le restreindre.

export const EXERCICES = [
  {
    id: "exs1",
    titre: "Retrouver un prix unitaire",
    groupe: "RECHERCHEV",
    objectif: "Utiliser RECHERCHEV pour retrouver le prix d'un article à partir de sa référence.",
    fichier: "exs1-recherchev-prix.xlsx",
    controles: [
    { cellule: "C2", libelle: "Prix ligne 2", attendu: 45, tolerance: 0.02 },
    { cellule: "C3", libelle: "Prix ligne 3", attendu: 350, tolerance: 0.02 },
    { cellule: "C4", libelle: "Prix ligne 4", attendu: 12.5, tolerance: 0.02 },
    { cellule: "C5", libelle: "Prix ligne 5", attendu: 11.4, tolerance: 0.02 },
    { cellule: "C6", libelle: "Prix ligne 6", attendu: 6.5, tolerance: 0.02 },
    { cellule: "C7", libelle: "Prix ligne 7", attendu: 620, tolerance: 0.02 },
    { cellule: "C8", libelle: "Prix ligne 8", attendu: 4.2, tolerance: 0.02 },
    { cellule: "C9", libelle: "Prix ligne 9", attendu: 22, tolerance: 0.02 },
    { cellule: "C10", libelle: "Prix ligne 10", attendu: 89, tolerance: 0.02 },
    { cellule: "C11", libelle: "Prix ligne 11", attendu: 7.6, tolerance: 0.02 },
    ],
  },
  {
    id: "exs2",
    titre: "Compléter une fiche produit",
    groupe: "RECHERCHEV",
    objectif: "Utiliser plusieurs RECHERCHEV pour retrouver désignation, catégorie et fournisseur.",
    fichier: "exs2-recherchev-fiche-produit.xlsx",
    controles: [
    { cellule: "B2", libelle: "Désignation REF109", attendu: "Chaussures de sécurité" },
    { cellule: "C2", libelle: "Catégorie REF109", attendu: "EPI" },
    { cellule: "D2", libelle: "Fournisseur REF109", attendu: "SecuEquip" },
    { cellule: "B3", libelle: "Désignation REF103", attendu: "Film étirable" },
    { cellule: "C3", libelle: "Catégorie REF103", attendu: "Emballage" },
    { cellule: "D3", libelle: "Fournisseur REF103", attendu: "EmballagePro" },
    { cellule: "B4", libelle: "Désignation REF107", attendu: "Chariot élévateur électrique" },
    { cellule: "C4", libelle: "Catégorie REF107", attendu: "Matériel" },
    { cellule: "D4", libelle: "Fournisseur REF107", attendu: "LogiMat" },
    { cellule: "B5", libelle: "Désignation REF102", attendu: "Carton simple cannelure" },
    { cellule: "C5", libelle: "Catégorie REF102", attendu: "Emballage" },
    { cellule: "D5", libelle: "Fournisseur REF102", attendu: "CartonPlus" },
    { cellule: "B6", libelle: "Désignation REF111", attendu: "Cadenas de sécurité" },
    { cellule: "C6", libelle: "Catégorie REF111", attendu: "Accessoire" },
    { cellule: "D6", libelle: "Fournisseur REF111", attendu: "SecuEquip" },
    { cellule: "B7", libelle: "Désignation REF105", attendu: "Gants de manutention" },
    { cellule: "C7", libelle: "Catégorie REF105", attendu: "EPI" },
    { cellule: "D7", libelle: "Fournisseur REF105", attendu: "SecuEquip" },
    { cellule: "B8", libelle: "Désignation REF110", attendu: "Sangle d'arrimage" },
    { cellule: "C8", libelle: "Catégorie REF110", attendu: "Accessoire" },
    { cellule: "D8", libelle: "Fournisseur REF110", attendu: "LogiMat" },
    { cellule: "B9", libelle: "Désignation REF112", attendu: "Extincteur portatif" },
    { cellule: "C9", libelle: "Catégorie REF112", attendu: "Sécurité" },
    { cellule: "D9", libelle: "Fournisseur REF112", attendu: "SecuEquip" },
    ],
  },
  {
    id: "exs3",
    titre: "Valoriser le stock",
    groupe: "RECHERCHEV",
    objectif: "Combiner RECHERCHEV et un calcul pour valoriser le stock d'un produit.",
    fichier: "exs3-recherchev-valorisation.xlsx",
    controles: [
    { cellule: "C2", libelle: "Prix REF201", attendu: 15, tolerance: 0.02 },
    { cellule: "D2", libelle: "Valeur REF201", attendu: 750, tolerance: 0.05 },
    { cellule: "C3", libelle: "Prix REF203", attendu: 120, tolerance: 0.02 },
    { cellule: "D3", libelle: "Valeur REF203", attendu: 480, tolerance: 0.05 },
    { cellule: "C4", libelle: "Prix REF205", attendu: 22.9, tolerance: 0.02 },
    { cellule: "D4", libelle: "Valeur REF205", attendu: 458, tolerance: 0.05 },
    { cellule: "C5", libelle: "Prix REF207", attendu: 5.1, tolerance: 0.02 },
    { cellule: "D5", libelle: "Valeur REF207", attendu: 509.99999999999994, tolerance: 0.05 },
    { cellule: "C6", libelle: "Prix REF209", attendu: 9.8, tolerance: 0.02 },
    { cellule: "D6", libelle: "Valeur REF209", attendu: 588, tolerance: 0.05 },
    { cellule: "C7", libelle: "Prix REF211", attendu: 2.3, tolerance: 0.02 },
    { cellule: "D7", libelle: "Valeur REF211", attendu: 690, tolerance: 0.05 },
    { cellule: "C8", libelle: "Prix REF202", attendu: 8.5, tolerance: 0.02 },
    { cellule: "D8", libelle: "Valeur REF202", attendu: 680, tolerance: 0.05 },
    { cellule: "C9", libelle: "Prix REF204", attendu: 3.4, tolerance: 0.02 },
    { cellule: "D9", libelle: "Valeur REF204", attendu: 510, tolerance: 0.05 },
    { cellule: "C10", libelle: "Prix REF206", attendu: 60, tolerance: 0.02 },
    { cellule: "D10", libelle: "Valeur REF206", attendu: 600, tolerance: 0.05 },
    { cellule: "C11", libelle: "Prix REF208", attendu: 200, tolerance: 0.02 },
    { cellule: "D11", libelle: "Valeur REF208", attendu: 600, tolerance: 0.05 },
    { cellule: "D13", libelle: "Total", attendu: 5866, tolerance: 0.1 },
    ],
  },
  {
    id: "exs4",
    titre: "Gérer les références inconnues",
    groupe: "SIERREUR",
    objectif: "Utiliser SIERREUR avec RECHERCHEV pour traiter les références absentes du catalogue.",
    fichier: "exs4-sierreur-recherchev.xlsx",
    controles: [
    { cellule: "C2", libelle: "Ligne 2", attendu: 10, tolerance: 0.02 },
    { cellule: "C3", libelle: "Ligne 3", attendu: "Référence inconnue" },
    { cellule: "C4", libelle: "Ligne 4", attendu: 8, tolerance: 0.02 },
    { cellule: "C5", libelle: "Ligne 5", attendu: 60, tolerance: 0.02 },
    { cellule: "C6", libelle: "Ligne 6", attendu: "Référence inconnue" },
    { cellule: "C7", libelle: "Ligne 7", attendu: 33, tolerance: 0.02 },
    { cellule: "C8", libelle: "Ligne 8", attendu: 5.5, tolerance: 0.02 },
    { cellule: "C9", libelle: "Ligne 9", attendu: 90, tolerance: 0.02 },
    { cellule: "C10", libelle: "Ligne 10", attendu: "Référence inconnue" },
    { cellule: "C11", libelle: "Ligne 11", attendu: 40, tolerance: 0.02 },
    ],
  },
  {
    id: "exs5",
    titre: "Statut de réapprovisionnement",
    groupe: "SI imbriqués",
    objectif: "Utiliser deux SI imbriqués pour classer un produit selon 3 niveaux d'urgence.",
    fichier: "exs5-si-imbriques.xlsx",
    controles: [
    { cellule: "F2", libelle: "Statut ligne 2", attendu: "Urgent" },
    { cellule: "F3", libelle: "Statut ligne 3", attendu: "À commander" },
    { cellule: "F4", libelle: "Statut ligne 4", attendu: "OK" },
    { cellule: "F5", libelle: "Statut ligne 5", attendu: "À commander" },
    { cellule: "F6", libelle: "Statut ligne 6", attendu: "Urgent" },
    { cellule: "F7", libelle: "Statut ligne 7", attendu: "OK" },
    { cellule: "F8", libelle: "Statut ligne 8", attendu: "Urgent" },
    { cellule: "F9", libelle: "Statut ligne 9", attendu: "À commander" },
    { cellule: "F10", libelle: "Statut ligne 10", attendu: "À commander" },
    { cellule: "F11", libelle: "Statut ligne 11", attendu: "Urgent" },
    { cellule: "F12", libelle: "Statut ligne 12", attendu: "OK" },
    { cellule: "F13", libelle: "Statut ligne 13", attendu: "À commander" },
    ],
  },
  {
    id: "exs6",
    titre: "Quantité totale par catégorie",
    groupe: "TCD",
    objectif: "Découvrir le tableau croisé dynamique pour regrouper des quantités par catégorie.",
    fichier: "exs6-tcd-quantite-categorie.xlsx",
    controles: [
    { cellule: "B25", libelle: "Total EPI", attendu: 170, tolerance: 0.5 },
    { cellule: "B26", libelle: "Total Emballage", attendu: 850, tolerance: 0.5 },
    { cellule: "B27", libelle: "Total Matériel", attendu: 22, tolerance: 0.5 },
    { cellule: "B28", libelle: "Total Accessoire", attendu: 300, tolerance: 0.5 },
    ],
  },
  {
    id: "exs7",
    titre: "Valeur de stock par fournisseur",
    groupe: "TCD",
    objectif: "Utiliser un TCD pour connaître la valeur de stock immobilisée par fournisseur.",
    fichier: "exs7-tcd-valeur-fournisseur.xlsx",
    controles: [
    { cellule: "B26", libelle: "Total SecuEquip", attendu: 3290, tolerance: 0.5 },
    { cellule: "B27", libelle: "Total LogiMat", attendu: 8100, tolerance: 0.5 },
    { cellule: "B28", libelle: "Total EmballagePro", attendu: 1670, tolerance: 0.5 },
    ],
  },
  {
    id: "exs8",
    titre: "Compter les références par catégorie",
    groupe: "TCD",
    objectif: "Utiliser un TCD en mode comptage plutôt qu'en mode somme.",
    fichier: "exs8-tcd-comptage-categorie.xlsx",
    controles: [
    { cellule: "B29", libelle: "Nombre EPI", attendu: 5, tolerance: 0.01 },
    { cellule: "B30", libelle: "Nombre Emballage", attendu: 7, tolerance: 0.01 },
    { cellule: "B31", libelle: "Nombre Matériel", attendu: 4, tolerance: 0.01 },
    { cellule: "B32", libelle: "Nombre Accessoire", attendu: 8, tolerance: 0.01 },
    ],
  },
  {
    id: "exs9",
    titre: "Retrouver un emplacement de stockage",
    groupe: "RECHERCHEV",
    objectif: "Réutiliser RECHERCHEV pour retrouver l'adresse de stockage d'un produit.",
    fichier: "exs9-recherchev-emplacement.xlsx",
    controles: [
    { cellule: "B2", libelle: "Emplacement REF905", attendu: "B01-01" },
    { cellule: "B3", libelle: "Emplacement REF901", attendu: "A01-01" },
    { cellule: "B4", libelle: "Emplacement REF910", attendu: "C02-01" },
    { cellule: "B5", libelle: "Emplacement REF903", attendu: "A02-01" },
    { cellule: "B6", libelle: "Emplacement REF912", attendu: "D01-02" },
    { cellule: "B7", libelle: "Emplacement REF907", attendu: "B02-02" },
    { cellule: "B8", libelle: "Emplacement REF902", attendu: "A01-02" },
    { cellule: "B9", libelle: "Emplacement REF909", attendu: "C01-03" },
    { cellule: "B10", libelle: "Emplacement REF906", attendu: "B01-04" },
    { cellule: "B11", libelle: "Emplacement REF911", attendu: "D01-01" },
    ],
  },
  {
    id: "exs10",
    titre: "Tableau de bord de stock complet",
    groupe: "Cas combiné",
    objectif: "Combiner RECHERCHEV, calcul, SI et TCD sur un cas complet de gestion de stock.",
    fichier: "exs10-cas-combine-tableau-de-bord.xlsx",
    controles: [
    { cellule: "D2", libelle: "Désignation REF401", attendu: "Casque de chantier" },
    { cellule: "E2", libelle: "Catégorie REF401", attendu: "EPI" },
    { cellule: "F2", libelle: "Prix REF401", attendu: 12.5, tolerance: 0.02 },
    { cellule: "G2", libelle: "Valeur REF401", attendu: 500, tolerance: 0.05 },
    { cellule: "H2", libelle: "Statut REF401", attendu: "OK" },
    { cellule: "D3", libelle: "Désignation REF402", attendu: "Gants de manutention" },
    { cellule: "E3", libelle: "Catégorie REF402", attendu: "EPI" },
    { cellule: "F3", libelle: "Prix REF402", attendu: 4.2, tolerance: 0.02 },
    { cellule: "G3", libelle: "Valeur REF402", attendu: 63, tolerance: 0.05 },
    { cellule: "H3", libelle: "Statut REF402", attendu: "À commander" },
    { cellule: "D4", libelle: "Désignation REF403", attendu: "Chaussures de sécurité" },
    { cellule: "E4", libelle: "Catégorie REF403", attendu: "EPI" },
    { cellule: "F4", libelle: "Prix REF403", attendu: 45, tolerance: 0.02 },
    { cellule: "G4", libelle: "Valeur REF403", attendu: 1125, tolerance: 0.05 },
    { cellule: "H4", libelle: "Statut REF403", attendu: "OK" },
    { cellule: "D5", libelle: "Désignation REF405", attendu: "Carton simple cannelure" },
    { cellule: "E5", libelle: "Catégorie REF405", attendu: "Emballage" },
    { cellule: "F5", libelle: "Prix REF405", attendu: 1.8, tolerance: 0.02 },
    { cellule: "G5", libelle: "Valeur REF405", attendu: 360, tolerance: 0.05 },
    { cellule: "H5", libelle: "Statut REF405", attendu: "OK" },
    { cellule: "D6", libelle: "Désignation REF406", attendu: "Film étirable" },
    { cellule: "E6", libelle: "Catégorie REF406", attendu: "Emballage" },
    { cellule: "F6", libelle: "Prix REF406", attendu: 15.8, tolerance: 0.02 },
    { cellule: "G6", libelle: "Valeur REF406", attendu: 126.4, tolerance: 0.05 },
    { cellule: "H6", libelle: "Statut REF406", attendu: "À commander" },
    { cellule: "D7", libelle: "Désignation REF407", attendu: "Étiquette code-barres" },
    { cellule: "E7", libelle: "Catégorie REF407", attendu: "Emballage" },
    { cellule: "F7", libelle: "Prix REF407", attendu: 9.9, tolerance: 0.02 },
    { cellule: "G7", libelle: "Valeur REF407", attendu: 495, tolerance: 0.05 },
    { cellule: "H7", libelle: "Statut REF407", attendu: "OK" },
    { cellule: "D8", libelle: "Désignation REF409", attendu: "Transpalette manuel" },
    { cellule: "E8", libelle: "Catégorie REF409", attendu: "Matériel" },
    { cellule: "F8", libelle: "Prix REF409", attendu: 350, tolerance: 0.02 },
    { cellule: "G8", libelle: "Valeur REF409", attendu: 1050, tolerance: 0.05 },
    { cellule: "H8", libelle: "Statut REF409", attendu: "À commander" },
    { cellule: "D9", libelle: "Désignation REF410", attendu: "Diable pliant" },
    { cellule: "E9", libelle: "Catégorie REF410", attendu: "Matériel" },
    { cellule: "F9", libelle: "Prix REF410", attendu: 89, tolerance: 0.02 },
    { cellule: "G9", libelle: "Valeur REF410", attendu: 1068, tolerance: 0.05 },
    { cellule: "H9", libelle: "Statut REF410", attendu: "OK" },
    { cellule: "D10", libelle: "Désignation REF411", attendu: "Sangle d'arrimage" },
    { cellule: "E10", libelle: "Catégorie REF411", attendu: "Matériel" },
    { cellule: "F10", libelle: "Prix REF411", attendu: 11.4, tolerance: 0.02 },
    { cellule: "G10", libelle: "Valeur REF411", attendu: 912, tolerance: 0.05 },
    { cellule: "H10", libelle: "Statut REF411", attendu: "OK" },
    { cellule: "D11", libelle: "Désignation REF412", attendu: "Chariot de manutention" },
    { cellule: "E11", libelle: "Catégorie REF412", attendu: "Matériel" },
    { cellule: "F11", libelle: "Prix REF412", attendu: 620, tolerance: 0.02 },
    { cellule: "G11", libelle: "Valeur REF412", attendu: 1240, tolerance: 0.05 },
    { cellule: "H11", libelle: "Statut REF412", attendu: "À commander" },
    { cellule: "B15", libelle: "Total EPI", attendu: 1688, tolerance: 0.1 },
    { cellule: "B16", libelle: "Total Emballage", attendu: 981.4, tolerance: 0.1 },
    { cellule: "B17", libelle: "Total Matériel", attendu: 4270, tolerance: 0.1 },
    ],
  },
];
